"
" .vimrc
"
"
" Setup Dein - teh Dark powered Vim/Neovim plugin manager
" https://github.com/Shougo/dein.vim
"
" install it first
  if (!isdirectory(expand("$HOME/.vim/repos/github.com/Shougo/dein.vim")))
    call system(expand("mkdir -p $HOME/.vim/repos/github.com"))
    call system(expand("git clone https://github.com/Shougo/dein.vim $HOME/.vim/repos/github.com/Shougo/dein.vim"))
  endif

" Mammouths are exctint!
  set nocompatible

" Load Dein
  set runtimepath+=~/.vim/repos/github.com/Shougo/dein.vim/

  call dein#begin(expand('~/.vim'))
  let pluginsExist = 0
" Let Dein manage itself
  call dein#add('Shougo/dein.vim')

" Install Plugins
  " languages
  call dein#add('elzr/vim-json', {'on_ft': 'json'})
  call dein#add('klen/python-mode', {'on_ft': 'python'})
 
  call dein#add('tpope/vim-markdown', {'on_ft': 'markdown'})
  call dein#add('suan/vim-instant-markdown', {'on_ft': 'markdown'})
 
  " features
  call dein#add('tpope/vim-fugitive')
  call dein#add('airblade/vim-gitgutter')
  
  call dein#add('mhinz/vim-sayonara')

  call dein#add('preservim/nerdtree')
  call dein#add('Xuyuanp/nerdtree-git-plugin')
  call dein#add('tiagofumo/vim-nerdtree-syntax-highlight')
  call dein#add('ryanoasis/vim-devicons')

  " interface
  call dein#add('vim-airline/vim-airline')
  call dein#add('vim-airline/vim-airline-themes')
  call dein#add('mhartington/oceanic-next')
  call dein#add('uguu-org/vim-matrix-screensaver')

" Test colorschemes for a while
"call dein#add('flazz/vim-colorschemes')
  call dein#add('xolox/vim-misc')
  call dein#add('xolox/vim-colorscheme-switcher')

"
  if dein#check_install()
    call dein#install()
  endif
  call dein#end()
 
" Required:
  filetype plugin indent on

" Let airline tell me my status
  set noshowmode
  set laststatus=2
  set noswapfile
  set showcmd
  set cmdheight=2
  set relativenumber number
  set wildmenu
  set wildmode=full
  set ruler
  set cursorline
  set display=uhex

  " Fix clipboard
  set clipboard=unnamedplus
  let mapleader = ','

  set tabstop=2 shiftwidth=2 expandtab
  
  filetype on
  syntax enable
  set background=dark
  colorscheme mytwilight

" Mappings 
  nmap <leader>- :NextColorScheme<CR>
  nmap <leader>f :NERDTreeToggle<CR>
                
"  nmap <leader>h :call <SID>SynStack()<CR>
"  function! <SID>SynStack()
"    if !exists("*synstack")
"      return
"    endif
"    echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
"  endfunc

  " Remap macros to Q and disable q
  nnoremap Q q
  nnoremap q <Nop>

  " disable the arrows keys :)
  noremap <left> <Nop>
  noremap <down> <Nop>
  noremap <up> <Nop>
  noremap <right> <Nop>
  inoremap <left> <Nop>
  inoremap <down> <Nop>
  inoremap <up> <Nop>
  inoremap <right> <Nop>

  nnoremap <C-h> <C-w>h
  nnoremap <C-j> <C-w>j
  nnoremap <C-k> <C-w>k
  nnoremap <C-l> <C-w>l

  " Swiss Keyboard Stuff
  nmap ç #
  nmap è [
  nmap ¨ ]
  nmap é {zz
  nmap à }zz

  " center around the cursor 
  nnoremap èè [[zz
  nnoremap ¨¨ ]]zz
  nnoremap [] []zz
  nnoremap ][ ][zz
  nnoremap <C-b> <C-b>zz
  nnoremap <C-f> <C-f>zz
  nnoremap <C-u> <C-u>zz
  nnoremap <C-d> <C-d>zz

  "let g:gitgutter_sign_column_always = 1
  set signcolumn=yes

" vim-airline
" ---------------------------------------------------------------{{{
  let g:airline#extensions#tabline#enabled = 1
  set hidden
  let g:airline#extensions#tabline#fnamemod = ':t'
  let g:airline#extensions#tabline#show_tab_nr = 1
  let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline_powerline_fonts = 1

"  if !exists('g:airline_symbols')
"      let g:airline_symbols = {}
"    endif
"    let g:airline_symbols.space = "\ua0"

  "let g:airline_theme='alduin'
  "let g:airline_theme='angr'
  "let g:airline_theme='atomic'
  "let g:airline_theme='aurora'
  "let g:airline_theme='ayu_mirage'
  "let g:airline_theme='badcat'
  "let g:airline_theme='badwolf'
  "let g:airline_theme='base16_3024'
  "let g:airline_theme='base16_apathy'
  "let g:airline_theme='base16_ashes'
  "let g:airline_theme='base16_atelierdune'
  "let g:airline_theme='base16_atelierforest'
  "let g:airline_theme='base16_atelierheath'
  "let g:airline_theme='base16_atelierlakeside'
  "let g:airline_theme='base16_atelierseaside'
  "let g:airline_theme='base16_bespin'
  "let g:airline_theme='base16_brewer'
  "let g:airline_theme='base16_bright'
  "let g:airline_theme='base16_chalk'
  "let g:airline_theme='base16_classic'
  "let g:airline_theme='base16_codeschool'
  "let g:airline_theme='base16_colors'
  "let g:airline_theme='base16color'
  "let g:airline_theme='base16_default'
  "let g:airline_theme='base16_eighties'
  "let g:airline_theme='base16_embers'
  "let g:airline_theme='base16_flat'
  "let g:airline_theme='base16_google'
  "let g:airline_theme='base16_grayscale'
  "let g:airline_theme='base16_greenscreen'
  "let g:airline_theme='base16_harmonic16'
  "let g:airline_theme='base16_hopscotch'
  "let g:airline_theme='base16_isotope'
  "let g:airline_theme='base16_londontube'
  "let g:airline_theme='base16_marrakesh'
  "let g:airline_theme='base16_mocha'
  "let g:airline_theme='base16_monokai'
  "let g:airline_theme='base16_oceanicnext'
  "let g:airline_theme='base16_ocean'
  "let g:airline_theme='base16_paraiso'
  "let g:airline_theme='base16_pop'
  "let g:airline_theme='base16_railscasts'
  "let g:airline_theme='base16_seti'
  "let g:airline_theme='base16_shapeshifter'
  "let g:airline_theme='base16_shell'
  "let g:airline_theme='base16_solarized'
  "let g:airline_theme='base16_spacemacs'
  "let g:airline_theme='base16_summerfruit'
  "let g:airline_theme='base16_tomorrow'
  "let g:airline_theme='base16_twilight'
  "let g:airline_theme='base16'
  "let g:airline_theme='behelit'
  "let g:airline_theme='biogoo'
  "let g:airline_theme='bubblegum'
  "let g:airline_theme='cobalt2'
  "let g:airline_theme='cool'
  "let g:airline_theme='dark_minimal'
  "let g:airline_theme='deus'
  "let g:airline_theme='distinguished'
  "let g:airline_theme='durant'
  "let g:airline_theme='fairyfloss'
  "let g:airline_theme='hybridline'
  "let g:airline_theme='hybrid'
  "let g:airline_theme='jellybeans'
  "let g:airline_theme='jet'
  "let g:airline_theme='kalisi'
  "let g:airline_theme='kolor'
  "let g:airline_theme='laederon'
  "let g:airline_theme='light'
  "let g:airline_theme='lucius'
  "let g:airline_theme='luna'
  "let g:airline_theme='minimalist'
  "let g:airline_theme='molokai'
  "let g:airline_theme='monochrome'
  "let g:airline_theme='murmur'
  "let g:airline_theme='onedark'
  "let g:airline_theme='papercolor'
  "let g:airline_theme='powerlineish'
  "let g:airline_theme='qwq'
  "let g:airline_theme='ravenpower'
  "let g:airline_theme='raven'
  
  let g:airline_theme='term'
  "let g:airline_theme='ubaryd'

  cnoreabbrev <expr> x getcmdtype() == ":" && getcmdline() == 'x' ? 'Sayonara' : 'x'
  nmap <leader>t :term<cr>
  nmap <leader>, :bnext<CR>
  nmap <leader>. :bprevious<CR>
  nmap <leader>1 <Plug>AirlineSelectTab1
  nmap <leader>2 <Plug>AirlineSelectTab2
  nmap <leader>3 <Plug>AirlineSelectTab3
  nmap <leader>4 <Plug>AirlineSelectTab4
  nmap <leader>5 <Plug>AirlineSelectTab5
  nmap <leader>6 <Plug>AirlineSelectTab6
  nmap <leader>7 <Plug>AirlineSelectTab7
  nmap <leader>8 <Plug>AirlineSelectTab8
  nmap <leader>9 <Plug>AirlineSelectTab9
  "set guifont=Sauce\ Code\ Pro\ Nerd\ Font\ Complete:h13
"}}}

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"zz" | endif
endif
