# ~/.bash_aliases

alias e='nvim'
alias ecv='e ~/.config/nvim/init.vim'
alias ecb='e ~/.bashrc'
alias ecw='e ~/.config/bspwm/bspwmrc'
alias ecs='e ~/.config/sxhkd/sxhkdrc'

# sort it, env!
alias env='env | sort'

# make od output readable
alias cod='od -A x -t x1 -c'
alias xod='od -A x -t x1z'


alias glk='gpg --keyid-format 0xLONG -k'
